server:
  port: 9000

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:;DB_CLOSE_ON_EXIT=TRUE;MODE=MySQL
    username: sa
    password:
    sqlScriptEncoding: UTF-8
  messages:
    basename: messages
    encoding: UTF-8
  
  resources:
    static-locations:
    - classpath:/META-INF/resources/
    - classpath:/resources/
    - classpath:/static/
    - classpath:/public/
    - file:/static
    
fuudoapp:
  album:
    imageDirectory: C:\static\image\